name: Update S&P500 Data

on:
  schedule:
    - cron: '0 20 * * 1-5'  # Every weekday at 20:00 UTC (23:00 Israel time)
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install yfinance pandas

    - name: Commit local changes (if any)
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Auto-commit before pull" || echo "Nothing to commit"

    - name: Pull latest changes
      run: git pull origin main --rebase

    - name: Run update script
      run: python update_data_backfill.py
      env:
        API_KEY: ${{ secrets.API_KEY }}

    - name: Commit and push updated data
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add sp500_data.csv
        git commit -m "Automated update of S&P500 data" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
